-- ==========================================
-- SQL SETUP UNTUK SAVE MONEY (RESET TOTAL)
-- ==========================================

-- 1. Hapus tabel lama (Hati-hati: Semua data di Supabase akan hilang!)
DROP TABLE IF EXISTS savings;
DROP TABLE IF EXISTS devices;

-- 2. Buat ulang tabel Savings
CREATE TABLE savings (
  id UUID PRIMARY KEY, -- ID akan dikirim dari aplikasi (UUID)
  amount NUMERIC NOT NULL,
  type TEXT CHECK (type IN ('income', 'expense')),
  note TEXT,
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sync_code TEXT NOT NULL
);

-- 3. Buat ulang tabel Devices (untuk limit perangkat)
CREATE TABLE devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_code TEXT NOT NULL,
  device_id TEXT NOT NULL
);

-- 4. Buat Index untuk performa
CREATE INDEX idx_savings_sync_code ON savings(sync_code);
CREATE INDEX idx_devices_sync_code ON devices(sync_code);

-- 5. Matikan RLS (Row Level Security) agar mudah diakses
-- (Sangat disarankan untuk memudahkan sinkronisasi awal)
ALTER TABLE savings DISABLE ROW LEVEL SECURITY;
ALTER TABLE devices DISABLE ROW LEVEL SECURITY;

-- SELESAI!
-- Silakan jalankan script ini di SQL Editor Supabase Anda.
